## NumPy

### O numpy nasceu a partir de 2 outros pacotes : Numeric e Numarray
### Esses pacotes foram criados em um esforça para prover uma solução open-source ao MatLab
### Numeric e Numarray foram descontinuados e NumPy nasceu com o melhor de ambos

In [1]:
# importando NumPy

import numpy as np

In [2]:
type(np)

module

### Criando Arrays

In [4]:
help(np.array)

Help on built-in function array in module numpy.core.multiarray:

array(...)
    array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an
        object whose __array__ method returns an array, or any
        (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then
        the type will be determined as the minimum type required
        to hold the objects in the sequence.  This argument can only
        be used to 'upcast' the array.  For downcasting, use the
        .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy
        will only be made if __array__ returns a copy, if obj is a
        nested sequence, or if a copy is needed to satisfy any of the other
        requirements (`dtype`, `order`, etc.).

In [5]:
vetor1=  np.array([0,1,2,3,4,5,6,7,8,9])

In [7]:
print(vetor1)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
type(vetor1)

numpy.ndarray

In [9]:
# criando uma lista. perceba como listas e arrays são objetos diferentes, com propriedades diferentes

lst =  [0,1,3,4,5,6,7,8,9]

In [10]:
lst

[0, 1, 3, 4, 5, 6, 7, 8, 9]

In [11]:
type(lst)

list

In [12]:
vetor1[0]

0

In [13]:
vetor1[6]

6

In [14]:
vetor1[0] = 100

In [15]:
vetor1

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [16]:
vetor1[1] = 'Novo Valor'

ValueError: invalid literal for int() with base 10: 'Novo Valor'

In [17]:
print(vetor1.shape)

(10,)


In [20]:
# A função arange cria um vetor contendo uma progressão aritmética 
# A partir de um intervalo - start, stop, step
vetor2 = np.arange(0.,4.5,.5)

In [21]:
vetor2

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

In [22]:
type(vetor2)

numpy.ndarray

In [23]:
np.shape(vetor2)

(9,)

In [24]:
print(vetor2.dtype)

float64


In [25]:
x = np.arange(1,10,0.25)
print(x)

[ 1.    1.25  1.5   1.75  2.    2.25  2.5   2.75  3.    3.25  3.5   3.75
  4.    4.25  4.5   4.75  5.    5.25  5.5   5.75  6.    6.25  6.5   6.75
  7.    7.25  7.5   7.75  8.    8.25  8.5   8.75  9.    9.25  9.5   9.75]


In [26]:
print(np.zeros(10))

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [27]:
z = np.eye(3)

In [28]:
z

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [30]:
# os calores passados como parâmetro, formam uma diagonal
d = np.diag([1,2,3,4,])

In [31]:
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [32]:
c = np.array([1+2j,3+4j, 5+6*1j])

In [33]:
c

array([ 1.+2.j,  3.+4.j,  5.+6.j])

In [34]:
b = np.array(['Python', 'R', 'Julia'])

In [35]:
b

array(['Python', 'R', 'Julia'], 
      dtype='<U6')

In [36]:
u = np.array([True, False, True, False])

In [37]:
u

array([ True, False,  True, False], dtype=bool)

In [38]:
# O mérodo linspace (linearly spaced vector) retorna um número de 
# valores igualmente distribuídos no intervalo especificado
np.linspace(0,10)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

In [39]:
print(np.linspace(0,5,10))

[ 0.          0.55555556  1.11111111  1.66666667  2.22222222  2.77777778
  3.33333333  3.88888889  4.44444444  5.        ]


help(np.alen)

## Criando Matrizes

In [41]:
# Criando uma matriz

matriz  = np.array([[1,2,3],[4,5,6]])

In [42]:
print(matriz)

[[1 2 3]
 [4 5 6]]


In [43]:
print(matriz.shape)

(2, 3)


In [44]:
matriz = np.ones((2,3))

In [45]:
print(matriz)

[[ 1.  1.  1.]
 [ 1.  1.  1.]]
